/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.jensrantil.tools.canary.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
